sudo: false
language: groovy
jdk:
- oraclejdk8
install: "./install-dependencies.sh"
script: "./travis-build.sh"
branches:
  only:
  - master
  - /^[0-9.]+.*$/
before_script:
- rm -rf build docs target gh-pages spring-security-oauth2-provider/build
- openssl aes-256-cbc -K $encrypted_c12e6c8df1af_key -iv $encrypted_c12e6c8df1af_iv -in github_deploy_key.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
env:
  global:
  - GIT_NAME="Brian Saville"
  - GIT_EMAIL="bksaville@gmail.com"
  # travis encrypt -a env.global 'GRAILS_CENTRAL_USERNAME=myusername'
  # travis encrypt -a env.global 'GRAILS_CENTRAL_PASSWORD=mypassword'
  # travis encrypt -a env.global 'BINTRAY_USER=myusername'
  # travis encrypt -a env.global 'BINTRAY_KEY=mypassword'
  - secure: aHPAUuip+gWj3pba1S6aqMkdVe5DQSN9hL/X0K5vY4HDrsJ3FE15CkcgFT9il02SiyIUJHY3esdnW/gaK55lzPCv0b6GRLrZfE/qSwpVzEyxyfBK15OYNzQm/jH10kJXUVbGhF0hpkLO8x9kVGJJsdKqSH5YsFYXFPEEL7xUo74=
  - secure: YMCir5j/i6T7IJd3D4QqQifyDlXComWMzCJI9W2QWvHbZ90YmRufIe+HlTtIP7HJEbJsXXR1f94dSiXTie0nbSWById27HwhnX30AcRExItn4MsgOhOeiHLR4946X8JSP6zcy+BiSAlpkxVDCHmEo6FW4onHt/G+spwcFZ1KbP8=
  - secure: dVM+jJNq6YB0o6Fw48aST6oZ7QusSoMoiUBD71/QOW679J1XIQHwaP2RYRqGY5b6A6ub6X7WaSkJ+d569BTL491S7buJxH0+OqSGrduxCxOIkc/9O9eX26WoZtnseKJy2SjclFJaomusLKtvTLrR3nz0SL2sMuAhkCqu0ksbk6o=
  - secure: ZKSGT4j+qrm/kGXIGCq4g8n5oDY7F20mevmA0e+y9/TSutNQZ4rz7f0DYp+I6kH4SZTM0RksSJNff/kFA3hE6VQqINcivU6dOIrVCFH0aWJO3nMo+7y37ZjhtfqkYpVxX5HIUmEINn80yL1aMEcFx2Ji5rc3+v3UVOWPnnlhfjY=
